# Generated by Django 4.0.3 on 2022-03-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='preço'),
        ),
        migrations.AlterField(
            model_name='itenorder',
            name='price_promotional',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='preço promocional'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total'),
        ),
    ]
