# Generated by Django 4.0.3 on 2022-03-19 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='nome do produto')),
                ('short_description', models.TextField(max_length=255, verbose_name='descricao curta')),
                ('long_description', models.TextField(verbose_name='descricao longa')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image/%Y/%m/', verbose_name='imagem')),
                ('product_slug', models.SlugField(unique=True, verbose_name='slug')),
                ('price_marketing', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço marketing')),
                ('price_marketing_promotional', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='preço marketing promocional')),
                ('product_type', models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], max_length=1, verbose_name='tipo de produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='variação')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='preço')),
                ('price_promotional', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='preço promocional')),
                ('quantity_stock', models.PositiveIntegerField(default=1, verbose_name='quantidade estoque')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'variação',
                'verbose_name_plural': 'variações',
            },
        ),
    ]
